### ISSUE TITLE
As a user, I want to create an account using an email and password that is not tied to google/gmail

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/ourhandsandfeet#191]
@cesarodriguez4 
sc2rs.com
has this function already, so you can use it as an example to get started (except we are not using Angular2).
https://github.com/PennStateSoftwareTest/FinalProjectPennState

Also, we are already using Aurelia Auth package to handle authentication with Google, so please use that process for this feature. We started with this example if this helps
https://github.com/paulvanbladel/aurelia-auth-sample

We also need form validation to check for the email
also, if the user enters any email that is @gmail.com
we should not accept it and tell them to just login using the Google Login button.

**Comment by cesarodriguez4** [comment]
@JoshuaVSherman So we can append another button above the "Login with Google" button. Can be a button with the label "Login with another account". What do you think?

**Comment by cesarodriguez4** [comment]
@JoshuaVSherman Sorry I went to say UNDER the Login with Google, not above.

**Comment by JoshuaVSherman** [comment]
need a login form with email and password then a button for that

**Comment by JoshuaVSherman** [comment]
Issue moved to [WebJamApps/combined-front #28](https://github.com/WebJamApps/combined-front/issues/28) via [**ZenHub**](https://www.zenhub.com/)
