### ISSUE TITLE
Obtain SSL certificate for the backend

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/ourhandsandfeet#304]
https://gethttpsforfree.com/

https://letsencrypt.org/

https://github.com/certbot/certbot

**Comment by LinuxBozo** [comment]
@JoshuaVSherman Wait long enough, and someone else will do it for you.  https://blog.heroku.com/announcing-automated-certificate-management

**Comment by JoshuaVSherman** [comment]
Awesome
