### ISSUE TITLE
Fix inconsistencies in the navigation menu styles

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/ourhandsandfeet#372]
* create a paper item style for hover over that is darker shade of the hand yellow-orange
* create a paper item style for the last clicked item that is a lighter shade of the hand yellow-orange
* there is currently no hover over on the logout icon, so fix this too please

**Comment by cesarodriguez4** [comment]
@JoshuaVSherman When you talk about a paper item style you mean to a background color with a texture of paper?  A background of the option selected and something like that, right?

**Comment by JoshuaVSherman** [comment]
The html tag is paper-item

**Comment by JoshuaVSherman** [comment]
@joshstoro @cesarodriguez4 

Josh Storo, would you please help our Cesar on this one if you get some time this weekend. Thanks

**Comment by JoshuaVSherman** [comment]
https://www.webcomponents.org/element/PolymerElements/paper-item

**Comment by JoshuaVSherman** [comment]
Issue moved to [WebJamApps/web-jam-front #149](https://github.com/WebJamApps/web-jam-front/issues/149) via [**ZenHub**](https://www.zenhub.com/)
